server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Auth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true
  main:
    web-application-type: servlet

  application:
    security:
      jwy:
        secret-key : 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D
        expiration: 86400000
        refresh-token:
          expiration: 604800000